version: '3'

services:
  casper-nctl:
    image: casper-nctl:rc3
    container_name: casper-nctl
    ports:
      - 11101-11105:11101-11105
      - 14101-14105:14101-14105
      - 18101-18105:18101-18105
    environment:
      PREDEFINED_ACCOUNTS: 'true'
      DEPLOY_DELAY: '5sec'
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: nctl-eventstore
      MYSQL_USER: nctl
      MYSQL_PASSWORD: passw0rd
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  nctlexplorer:
    image: casper-nctl-explorer:devnet
    container_name: webexplorer
    tty: true
    environment:
      Casper.Network.SDK.Web__NodeAddress: 'http://casper-nctl:11101'
      Casper.Network.SDK.Web__SSEHost: 'casper-nctl'
      MySqlConnection: 'Server=mysql;Database=nctl-eventstore;User Id=nctl;Password=passw0rd;'
    ports:
      - 8080:80
volumes:
  db_data:
    driver: local